#! /bin/sh
# \
exec make -I../.. -f "$0" "$@"
#
# -*- coding: utf-8 -*-
#
# Copyright © 2018 Philipp Büttgenbach
#
# This work is licensed under the Creative Commons
# Attribution-ShareAlike 4.0 International License.  To view a copy of
# this license, visit http://creativecommons.org/licenses/by-sa/4.0/.
#

piece = Ignace_Pleyel-opus_8

archive_extra_files = ../../output-duos.ily

include rules.make

# Local Variables:
# coding: utf-8
# mode: Makefile
# End:
